export default {
	INIT: 'INIT',

	USER_SELECTED: 'USER_SELECTED',
	USERS_FETCH_ING: 'USERS_FETCH_ING',
	USERS_FETCH_SUCCESS: 'USERS_FETCH_SUCCESS',
	USERS_FETCH_FAIL: 'USERS_FETCH_FAIL',

	CANCEL_INFO_FETCH: 'CANCEL_INFO_FETCH',

	USER_INFO_ING: 'USER_INFO_ING',
	USER_INFO_SUCCESS: 'USER_INFO_SUCCESS',
	USER_INFO_FAIL: 'USER_INFO_FAIL',

	WS_OPEN_PENDING: 'WS_OPEN_PENDING',
  WS_OPEN_SUCCESS: 'WS_OPEN_SUCCESS',
  WS_OPEN_FAIL: 'WS_OPEN_FAIL',
  WS_CLOSING: 'WS_CLOSING',
  WS_CLOSED: 'WS_CLOSED',
  WS_MSG_RECEIVED: 'WS_MSG_RECEIVED',
  WS_MSG_SEND: 'WS_MSG_SEND',
}
