export default {
	USER_SELECTED: 'USER_SELECTED',
	USERS_FETCH_ING: 'USERS_FETCH_ING',
	USERS_FETCH_SUCCESS: 'USERS_FETCH_SUCCESS',
	USERS_FETCH_FAIL: 'USERS_FETCH_FAIL',

	USER_INFO_ING: 'USER_INFO_ING',
	USER_INFO_SUCCESS: 'USER_INFO_SUCCESS',
	USER_INFO_FAIL: 'USER_INFO_FAIL',

	RCV_MSG: 'RCV_MSG',
	SND_MSG: 'SND_MSG',
}
